name : NetCore-CustomerApi-CI
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - WebApplication3/*
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  buildConfiguration: 'Release'
 
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/WebApplication3*.csproj'
  displayName: 'Restore Nuget Packages'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/WebApplication3*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
  displayName: 'Build projects'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/WebApplication3.csproj'
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Output --no-restore'
    modifyOutputPath: false
  displayName: 'Publish WebApplication3'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AppServiceGeany'
    appType: 'webAppLinux'
    appName: 'MentorshipGeanyAppService'
    package: '$(Build.ArtifactStagingDirectory)/Output/**/*.zip'

